version: "3.8"
services:
  db:
    restart: always
    image: postgres:12.3
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "lilya"
    expose:
      - "5432"
    command: >-
        --jit=false
    ports:
      - "5432:5432"
